name: Export label config
on:
  # You can run this with every event, but it's better to run it only when you actually need it.
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/export-label-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          raw-result: false
          add-aliases: true
      # By default every label entry will have an `aliases` property set to an empty array.
      # It's for EndBug/label-sync, if you don't want it you cans set this to `false`
